#  Quality Armory: A quality gun plugin similar to CrackShot.
#
#FAQ:
#Q: I do not want to use your resourcepack. How do I disable it?
#A: Set "useDefaultResourcepack" to false if you do not want any resourcepacks. If you want to use another resourcepack instead, set "DefaultResoucepackOverride" to true and replace "DefaultResoucepack" with the link to the resourcepack you want to use.
#
#Q: I want to disable friendly fire, but the "FriendlyFireEnabled" value does not do anything
#A: Friendly fire uses Parties to determine who is a part of the same group. Download "Parties" to enable this feature
#
#Q: I want guns to degrade as they are used.
#A: Set "EnableWeaponDurability" to true. Note that old guns will break because of this, so users will need to craft/buy new guns.
#
#Q:I do not want users to be able to shoot through leaves
#A: Set the "leaves" value under "BlockBullets" to true
#
#Q:When players join, I want them to automatically download the resourcepack.
#A: Set "sendOnJoin" to true to force all users to use the resourcepack
#
#Q: I want the bullet count to show on the items icon.
#A: Set "enableVisableBulletCounts" to true. Note that minecraft was not built to handle stacks of hoes, so there is a CHANCE for that the gun may get glitched or duplicated. 
#
#Q: My server is lagging because there are too many particles when shooting
#A: Increase "BulletTrailsSpacing" from 0.5 to 1 or 2.
#
#Q: One of your guns is overpowered/too cheap/ unbalanced
#A: You can configure the price, damage, and crafting ingredients under the "Weapon","Ammo","Misc", and "crafting" tabs
#
#Q: I want to add new guns/ammo to the plugin
#A: Follow this tutoiral: https://www.spigotmc.org/wiki/how-to-create-new-guns-with-quality-armory/

ENABLE-DEBUG: false
useDefaultResourcepack: true
sendOnJoin: false
sendTitleOnJoin: false
DefaultResoucepackOverride: false
DefaultResoucepack: https://www.dropbox.com/s/3bllojuzjpbbxto/QualityArmoryv1.0.11.zip?dl=1
hideTextureWarnings: false
Auto-Detect-Resourcepack: false

Enable_Headshot_Instantkill: true

UnlimitedPistolAmmo: false
UnlimitedShotgunAmmo: false
UnlimitedRifleAmmo: false
UnlimitedSMGAmmo: false
UnlimitedSniperAmmo: false
UnlimitedRocketAmmo: false
UnlimitedLazerAmmo: false
EnableWeaponDurability: false
FriendlyFireEnabled: false
BulletDetection:
  step: 0.1
BlockBullets:
  door: false
  halfslabs: false
  leaves: false
  water: false
enableInteract:
  Chests: false
overrideAnvil: false
enableBulletTrails: true
BulletTrailsSpacing: 0.5
enableVisableBulletCounts: false
enableReloadingWhenSwapToOffhand: true
enableExplosionDamage: false
enableExplosionDamageDrop: false
enableCrafting: true
enableShop: true
AUTO-UPDATE: true
Swap-Reload-and-Shooting-Controls: false
enable_lore_gun-info_messages: true
enable_lore_control-help_messages: true
BulletWounds:
  InitialBloodLevel: 100.0
  BloodIncreasePerSecond: 0.01
  Medkit_Heal_Bloodloss_Rate: 0.05
  enableBleeding: false
allowGunReload: true
Bullet-Particle-Type: FIREWORKS_SPARK
ACCEPTED-BULLET-PARTICLE-VALUES: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Particle.html
gunMaterialType: DIAMOND_AXE
IronSightsOnRightCLick: false
Crafting:
  Grenades:
  - IRON_INGOT,0,6
  - SULPHUR,0,10
  Kevlarnk1:
  - IRON_INGOT,0,15
  - REDSTONE,0,5
Weapon:
  Grenade:
    Price: 800.0
    radiusdamage: 10.0
    radius: 5.0
  Kevlarmk1:
    DamageThreshold: 1
    Price: 1200.0
