#  Quality Armory: A quality gun plugin similar to CrackShot.
#
#FAQ:
#Q: I do not want to use your resourcepack. How do I disable it?
#A: Set "useDefaultResourcepack" to false if you do not want any resourcepacks. If you want to use another resourcepack instead, set "DefaultResoucepackOverride" to true and replace "DefaultResoucepack" with the link to the resourcepack you want to use.
#
#Q: I want to disable friendly fire, but the "FriendlyFireEnabled" value does not do anything
#A: Friendly fire uses Parties to determine who is a part of the same group. Download "Parties" to enable this feature
#
#Q: I want guns to degrade as they are used.
#A: Set "EnableWeaponDurability" to true. Note that old guns will break because of this, so users will need to craft/buy new guns.
#
#Q:I do not want users to be able to shoot through leaves
#A: Set the "leaves" value under "BlockBullets" to true
#
#Q:When players join, I want them to automatically download the resourcepack.
#A: Set "sendOnJoin" to true to force all users to use the resourcepack
#
#Q: I want the bullet count to show on the items icon.
#A: Set "enableVisableBulletCounts" to true. Note that minecraft was not built to handle stacks of hoes, so there is a CHANCE for that the gun may get glitched or duplicated. 
#
#Q: My server is lagging because there are too many particles when shooting
#A: Increase "BulletTrailsSpacing" from 0.5 to 1 or 2.
#
#Q: One of your guns is overpowered/too cheap/ unbalanced
#A: You can configure the price, damage, and crafting ingredients under the "Weapon","Ammo","Misc", and "crafting" tabs
#
#Q: I want to add new guns/ammo to the plugin
#A: Follow this tutoiral: https://www.spigotmc.org/wiki/how-to-create-new-guns-with-quality-armory/

unknownTranslationKeyFixer: false
Enable_Creation_Of_Default_Files: true
KickPlayerIfDeniedResourcepack: false
hideTextureWarnings: false

#Use this if you are expierincing a problem. 
ENABLE-DEBUG: false

#Enables weapon duribility and degredation on every shot.
EnableWeaponDurability: false

#Swaps the reload button to LMB and shoot to RMB, if you are more familiar with Crackshot's shooting controls
Swap-Reload-and-Shooting-Controls: false

#Resourcepack values
useDefaultResourcepack: true
DefaultResourcepackOverride: false
DefaultResourcepack: https://www.dropbox.com/s/7xn1a6vmazc29zg/QualityArmoryv1.0.14.zip?dl=1
Auto-Detect-Resourcepack: false

#Determines if the resourcepack should be sent when a player joins.
sendOnJoin: false
sendTitleOnJoin: false

#Experminetal: Headshots will have more features in the future
Enable_Headshot_Instantkill: true
Enable_Headshot_Notification_Sound: true
Enable_Headshot_Sounds: true

#If parties is enabled, FriendlyFire will determine if players can shoot members of their party.
FriendlyFireEnabled: false

#This is used for calculating the bullet step. 
#If you're server is lagging for every shot, increase this value. 
#If you want more accurate shots around corners, decrease it.
BulletDetection:
  step: 0.1 
#By default, these blocks will allow bullets. If you want glass or leaves to stop bullets, set the values to true.
BlockBullets:
  door: false
  halfslabs: false
  leaves: false
  water: false
  glass: false
#By default, chests cannot be interacted with when holding a gun to make sure the user won't open a menu while firing.
enableInteract:
  Chests: false
#If set to true, overrideAnvil will let the anvil turn into a gun-crafting station.
overrideAnvil: false
#Determines if bullets will leave a trail of particles. Set to false if your players/server can't handle the particles AT ALL. 
enableBulletTrails: true
#Determines the spacing between particles. If your players/server can't hande that many particles, increase the values
BulletTrailsSpacing: 0.5

#UNSUPPORTED: Enable bullet counts for guns.
enableVisibleBulletCounts: false

#Reloads the gun if the user tries to swap it to the off hand.
enableReloadingWhenSwapToOffhand: true

#EXPERIMENTAL: Explosion damage
enableExplosionDamage: false
enableExplosionDamageDrop: false

#Enables the shop and crafting menu.
enableCrafting: true
enableShop: true

#Determines if the plugin should auto-update. Disable this if you need a specific version of QA.
AUTO-UPDATE: true

enable_lore_gun-info_messages: true
enable_lore_control-help_messages: true
BulletWounds:
  InitialBloodLevel: 100.0
  BloodIncreasePerSecond: 0.01
  Medkit_Heal_Bloodloss_Rate: 0.05
  enableBleeding: false
  
#Determines if a player can reload a gun. 
allowGunReload: true

IronSightsOnRightClick: false
#Determines how long the till the Resourcepack message should be sent.
SecondsTillRPIsSent: 0.0

#Determines if block break textures should appear
Break-Block-Texture-If-Shot: true