main: me.zombie_striker.qg.Main
version: 1.1.99
name: QualityArmory
commands:
  QualityArmory:
    description: Create images using blocks
    aliases: [qa]
permissions:
  qualityarmory.*:
    description: Gives access to all PixelPrinter commands
    children:
      qualityarmory.admin: true
  qualityarmory.admin:
    description: Gives access to all PixelPrinter commands
    children:
      qualityarmory.give: true
      qualityarmory.create: true
      qualityarmory.createnewitem: true
      qualityarmory.reload: true
      qualityarmory.getopengunslot: true
      qualityarmory.getmaterialsused: true
      qualityarmory.default: true
      qualityarmory.debugmessages: true
  qualityarmory.default:
    default: true
    description: Gives access to all PixelPrinter commands
    children:
      qualityarmory.craft: true
      qualityarmory.shop: true
      qualityarmory.usegun: true
softdepend: [Vault, Parties, WorldGuard, ViaVersion, ViaRewind, LightAPI, Citizens]
author:
   Zombie_Striker